### PR TITLE
Modularize visualization and add MSE function

### PR DESCRIPTION
**Pull request by yunliangchen**
Modularized the `visualize` function by splitting it into `compute_traj_pred_actual_actions` and `visualize`, and added a `compute_mse` function that mimics the `visualize` function (looping through sampled trajectories from the datasets and calling `compute_traj_pred_actual_actions` for each trajectory), and logging the MSE metrics (that are part of the logging into wandb).

Just as a note, **diffusion_policy.py** and `BC_Transformer` in **bc.py** have the exact same 3 functions (`compute_traj_pred_actual_actions`, `visualize`, `compute_mse`). These 3 functions probably work for other classes in **bc.py**, so moving that to the base `BC` class may be a good idea.

Other files that are modified:
- `make_model_prediction_plot` in **algo.py**: slight modification to accommodate changes in `visualize`
- **config/base_config.py, scripts/config_gen/helper.py**: adding fields to `self.experiment.vis` and `self.experiment.mse`
- **bc_transformer.json, bc.json, diffusion_policy.json**: adding `mse` fields

### CODE REVIEW

**Comment by yunliangchen** [comment]
Added support for a validation set for R2D2 data. Changes are in:

- **config_gen/helper.py**: Added a function `split_datasets` that splits the dataset_paths. At the bottom, set `"experiment.validate" `to True and add `"experiment.validation_epoch_every_n_steps"`.
- **config_gen/bc_xfmr_gen.py**: Added keys `"train.hdf5_filter_key"` and `"train.hdf5_validation_filter_key"`, which calls `split_datsets` to generate the train set paths and val set paths
- **config_gen/diffusion_gen.py**: Same modifications as **bc_xfmr_gen.py**
- **train_utils.py**: In `dataset_factory`, set `ds_kwargs["filter_by_attribute"]` according to `filter_by_attribute`

**Comment by yunliangchen** [comment]
Updated **algo/bc.py** and **algo/diffusion_policy.py** to support validation set in visualization and MSE calculation: `inference_datasets_mapping = {"Train": training_sampled_data, "Valid": validation_sampled_data} ` instead of just `inference_datasets_mapping = {"Train": training_sampled_data}`

**Comment by yunliangchen** [comment]
I incorporated the comments. Specifically:

- `compute_traj_pred_actual_actions`, `visualize`, `compute_mse` are removed from **diffusion_policy.py** and `BC_Transformer` in **bc.py** and moved to `PolicyAlgo` class in **algo.py**
- Changes in **config_gen/helper.py**, **config_gen/bc_xfmr_gen.py**, **config_gen/diffusion_gen.py**, and **train_utils.py** for validation set have been removed

**Review by snasiriany — APPROVED** [review]
Thanks @yunliangchen! Merging in now.

**Pull request merged**
