### PR TITLE
Modules registry for supporting custom backbone networks

### PR DESCRIPTION
**Pull request by arhanjain**
Addresses #189 

The implementation consists of adding a registry to the Module class so that all child classes are registered by their name into the registry upon `__init_subclass__`. This allows one to initialized backbones (like in parameters of VisualCore) through the registry rather than using `eval` which only allows models from base_nets.py

Example script coming soon

### CODE REVIEW

**Comment by danfeiX** [comment]
Thanks! I think it'd be much better to move this to EncoderCore in obs_core.py, as many classes that inherits `Module` are not necessarily encoders

**Comment by arhanjain** [comment]
looks like there's already a encoder registry, so we just need to modify the way the VisualCore class initializes its backbone!

**Review by danfeiX — APPROVED** [review]
LGTM!

**Comment by amandlek** [comment]
Thanks @arhanjain for your contribution!

**Pull request merged**
